# networks:
#   my-network:
#     driver: bridge

services:
  angular:
    container_name: angular
    # Nombre del servicio para la aplicación Angular
    build:
      # Ruta al Dockerfile del frontend
      context: ./client
      dockerfile: Dockerfile
    ports:
      # Mapeo del puerto del contenedor al puerto local (opcional)
      - "80:80"
  
  nodejs:
    container_name: nodejs
    # Nombre del servicio para el backend Node.js
    build:
      # Ruta al Dockerfile del backend
      context: ./api
      dockerfile: Dockerfile
    ports:
      # Puerto en el que escucha el servidor Node.js en el contenedor
      - "3000:3000"
    depends_on:
      # Dependencia del servicio de MongoDB
      - mongodb
    entrypoint: ["sh", "-c", "node crearBBDD.js && npm start"]
    # networks:
    #   - my-network
    

  mongodb:
    container_name: mongodb
    # Configuración para el contenedor de MongoDB
    image: mongo
    ports:
      # Puerto en el que escucha MongoDB en el contenedor
      - "27017:27017"
    # networks:
    #   - my-network
